account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    url(r'signup/$', views.SignupUI.as_view(), name='signup'),
    url(r'login/$', views.LoginUI.as_view(), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout')
]

bearcut/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingUI.as_view(), name='landing'),
    url('', include('account.urls', namespace='account')),
    url('', include('django.contrib.auth.urls')),
    url('', include('booking.urls', namespace='booking'))
]

booking/urls.py
from django.conf.urls import url
from . import views

app_name = 'booking'

urlpatterns = [
    url(r'book/$', views.BookUI, name='book'),
    url(r'confirm/$', views.ConfirmUI, name='confirm'),
    url(r'history/$', views.HistoryUI, name='history')
]

account/models.py
from django.db import models
from django.contrib import auth

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


PAYMENT = (
    ('cash','CASH'),
    ('credit_card','CREDIT CARD')
)

STATUS = (
    ('pending','PENDING'),
    ('paid','PAID')
)

class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    phone_number = PhoneNumberField(null=True)
    payment_type = models.CharField(max_length=10, choices=PAYMENT, default='cash')
    status = models.CharField(max_length=10, choices=STATUS, default='pending')
    created = models.DateTimeField(auto_now_add=True)

account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

class SignupForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Choosen password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Type password again'}))

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

booking/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from phonenumber_field.formfields import PhoneNumberField
from account.models import User
from .models import Book


class BookForm(forms.ModelForm):

    date = forms.DateField(widget=forms.SelectDateWidget())
    time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    phone_number = PhoneNumberField()

    class Meta:
        fields = ('date','time','phone_number',)
        model = Book


class ConfirmForm(forms.ModelForm):

    PAYMENT = [
        ('cash','CASH'),
        ('credit_card','CREDIT CARD')
    ]

    payment_type = forms.ChoiceField(choices=PAYMENT, widget=forms.RadioSelect())

    class Meta:
        fields = ('payment_type',)
        model = Book


class NameForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('first_name','last_name',)

account/views.py
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic import CreateView
from django.views import generic
from . import forms

class SignupUI(CreateView):
    form_class = forms.SignupForm
    success_url = reverse_lazy('login')
    template_name = 'account/signup.html'

class LoginUI(generic.FormView):
    form_class = forms.LoginForm
    success_url = reverse_lazy('landing')
    template_name = 'account/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginUI, self).form_valid(form)
        else:
            return self.form_invalid(form)

bearcut/views.py
from django.views.generic import TemplateView

class LandingUI(TemplateView):
    template_name = 'bearcut/index.html'

booking/views.py
import re
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import BookForm, ConfirmForm, NameForm
from .models import Book


@login_required
def BookUI(request):

    # Show booking form with POST request
    form = BookForm(request.POST)

    if form.is_valid():
        # Preprocessing for sessions
        date = json.dumps(form.cleaned_data['date'],cls=DjangoJSONEncoder)
        time = json.dumps(form.cleaned_data['time'],cls=DjangoJSONEncoder)
        date_re = re.sub('[^a-zA-Z0-9-_*.]','', date)
        time_re = time.replace('"', '')
        phone_format = form.cleaned_data['phone_number']
        phone_number = str(phone_format).replace('+', '')

        # Initiate sessions
        request.session['date'] = date_re
        request.session['time'] = time_re
        request.session['phone_number'] = phone_number

        # Compare selected date and time to records in database
        check_date_time = Book.objects.filter(date=date_re, time=time_re).values('date', 'time')

        # Check availability the selected date and time
        if check_date_time:
            # Show alert message
            messages.info(request, 'Sorry, someone has made an appointment at the selected time. Please choose another time!')
        else:
            # Go to confirm page
            return HttpResponseRedirect('confirm/')

    else:
        # Reload  form if form is invalid
        form = BookForm()

    # Context dictionary for template tagging
    context = {'form': form}

    # Return an HttpResponse by combining template and context dictionary
    return render(request, 'booking/new.html', context)


@login_required
def ConfirmUI(request):

    # Declare variable for sessions
    date = request.session['date']
    time = request.session['time']
    phone_number = request.session['phone_number']

    # Show confirm form and name form with POST request
    confirmform = ConfirmForm(request.POST)
    ## Instance model relation with the current user
    userform = NameForm(request.POST, instance=request.user)

    if confirmform.is_valid() and userform.is_valid():
        # Create new object for Book model
        book = Book()
        # Initiate sessions to record in database
        book.date = date
        book.time = time
        ## Initiate form field data to record in database
        book.service = confirmform.cleaned_data['payment_type']
        book.phone_number = phone_number
        # Initiate user to the current user
        book.user = request.user
        # Save all record to database
        book.save()
        # Save all user change info field to database
        userform.save()

        # Finish booking step form, go to booking history
        return HttpResponseRedirect('history/')

    else:
        # Reload confirm form and user form if form is invalid
        confirmform = ConfirmForm()
        userform = NameForm(instance=request.user)

    context = {'confirmform': confirmform, 'nameform': userform}

    return render(request, 'booking/confirm.html', context)


@login_required
def HistoryUI(request):

    # Show booking history of the current user
    history = Book.objects.filter(user=request.user)

    context = {'history': history}

    return render(request, 'booking/history.html', context)

booking/templates/booking/confirm.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Book a new appointment - Bearcut</title>
  </head>
  <body>
    <p><h3>Yes, we are available.</h3><br>
    <strong>Confirmation</strong><br>
      Please complete this form out.</p>
    <form method="post">
        {% csrf_token %}
        {{ nameform.as_p }}
        {{ confirmform.as_p }}
        <input type="submit" value="Book now">
      </form>
      <br/>
  </body>
</html>

booking/templates/booking/history.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Booking History - Bearcut</title>
  </head>
  <body>
    <p><strong>History</strong><br>
    This is your recent haircut.</p>
    {% for book in history %}
    <ul>
      <li>Booking created: {{ book.created }}</li>
      <li>For {{ book.date }} on {{ book.time }}</li>
      <li>Name: {{ user.first_name }} {{ user.last_name }}</li>
      <li>Payment type: {{ book.payment_type }}</li>
      <li>Status: {{ book.status }}</li>
    </ul>
    {% endfor %}
  </body>
</html>

booking/templates/booking/new.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Book a new appointment - Bearcut</title>
  </head>
  <body>
    <p><strong>Hello</strong>, {{ user.username }}! <br>
      Ready to cut your hair?<br>
    </p>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li> {{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Book">
      </form>
  </body>
</html>

templates/bearcut/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Bearcut - Jakarta</title>
  </head>
  <body>
    <h1>Bearcut</h1>
    <ul>
      <li><a href="admin/">Admin</a></li>
      <li><a href="{% url 'account:signup' %}">Sign up</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'account:logout' %}">Sign out</a></li>
      {% else %}
        <li><a href="{% url 'account:login' %}">Sign in</a></li>
      {% endif %}
      {% if user.is_authenticated %}
        <li><a href="{% url 'booking:book' %}">Book</a></li>
        <li><a href="{% url 'booking:history' %}">History</a></li>
      {% else %}
      {% endif %}
    </ul>
  </body>
</html>